version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root5412@B
      MYSQL_DATABASE: pbdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pb-network
  
  tomcat:
    build: .
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=pbdb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root5412@B
    ports:
      - "8080:8080"
    networks:
      - pb-network
networks:
  pb-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
